version: "3.7"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    ports:
      - '3000:3000'
    volumes:
      - ./data:/var/lib/grafana
    networks:
      - grafana-net
  influxdb:
    image: influxdb:1.0
    container_name: influxdb
    user: root
    ports:
      - '8086:8086'
      - '8083:8083'
      - '25826:25826/udp'
    environment:
      INFLUXDB_DB: telegraph 
    volumes:
      - ./influxdb:/var/lib/influxdb
    networks:
      - grafana-net

networks:
  grafana-net:
    driver: bridge

volumes:
  grafana-date:
  influxdb-data: